FROM ubuntu:20.04

RUN apt update
RUN apt install -y python3.8 pipenv
RUN ln /usr/bin/python3.8 /usr/bin/python

WORKDIR /home

COPY Pipfile* ./
COPY .env .

RUN pipenv install --system

COPY dbaccess/ /home/

EXPOSE 5001
